import Footer from '@components/Footer';
import Header from '@components/Header/page';
import '@styles/globals.css';

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className='bg-primary bg-[url("/block_pink.svg")] bg-no-repeat'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
